name: flutter_fullscreen
description: "Allow setting and listening to fullscreen state on all platforms."
version: 1.0.0
homepage: https://github.com/j7126/full_screen

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.1
  window_manager: ^0.3.9

dev_dependencies:
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
